### ISSUE TITLE
Nominating @JounQin as a maintainer of @mdx-js

### ISSUE THREAD

**Issue by wooorm** [mdx-js/governance#1]
Hi folks!

@JounQin [suggested](https://spectrum.chat/mdx/general/rfc-dedicate-eslint-mdx-repo-to-mdxjs-organization~795aff97-91be-4665-b383-be5c474d6980) to move eslint-mdx to the mdx-js organization.

Joun has [opened issues/prs (3)](https://github.com/search?q=org%3Amdx-js+author%3AJounQin&type=Issues), [commented (3)](https://github.com/search?q=org%3Amdx-js+commenter%3AJounQin&type=Issues), and landed a [couple of commits (2)](https://github.com/search?q=org%3Amdx-js+author%3AJounQin&type=Commits) in the org already. Joun is interested in helping to maintain the organization, and to keep on working on eslint-mdx from within the org.

I therefore move to [nominate @JounQin as a maintainer of mdx](https://github.com/unifiedjs/collective/blob/master/members.md#motion-to-nominate-a-maintainer). Any collective core team maintainer (@mdx-js/core) may vote.

- Organization: @mdx-js
- Teams: maintainers
- Full name: Joun Qin
- GH: @JounQin
- npm: ?

**Comment by JounQin** [comment]
My npm account is still `jounqin`.
Thx for this.

**Comment by wooorm** [comment]
You’re added! Welcome Joun! 👋 Tooling will now invite you to orgs, and set you up with the correct permissions.

Could you move the project over to the mdx-js org, and add me as an admin to npm packages? Following that, tooling will then give the correct people the correct rights to the project.

You are now a [merger](https://github.com/unifiedjs/collective/blob/master/permissions.md) on the whole mdx-js organization. You will loose npm publish access to eslint-mdx. The reason for that is that we, for security reasons, use two steps to merge and release projects, typically by different people.

Please take the time to read through the [collective governance repository](https://github.com/unifiedjs/collective) to find out what we expect from you, and what you can expect from us. You are welcome here, and to make sure other people are welcome as well, please adhere to our [code of conduct](https://github.com/unifiedjs/collective/blob/master/code-of-conduct.md).

@johno is lead of the MDX organization, and MDX is a bit different than the rest of the collective in some matters like code style, so please check in with John for MDX relating questions.
You are also free to ping other members, including me! But I try to keep a bit of a broader view of the whole collective

**Comment by JounQin** [comment]
Thank your guys, I've add @wooorm as admin of eslint-mdx and eslint-plugin-mdx.
I'll read related documentations ASAP.

Are there any maintainers going to reviewing eslint-mdx's code base? Really excited to hear advices
from you guys.

Personally, I'm a newbie to be a maintainer OSS, I'll learn hard to be a good maintainer.

Thanks guys, again. Cheers!
